export const address = [
    {
        modelType: 'field',
        id: '622040bd83ee70124c825bd7',
        type: 'TEXT',
        dataType: 'STRING',
        fieldName: 'current_address',
        fieldDisplayName: 'Current Address',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: '',
        helpText: 'Enter any remarks while filling personal information page',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bd7',
        type: 'TEXT',
        dataType: 'STRING',
        fieldName: 'permanent_address',
        fieldDisplayName: 'Permanent Address',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: '',
        helpText: 'Enter any remarks while filling personal information page',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      }
]