export const basicDetails = [
  {
    modelType: 'details',
    id: '622040bd83ee70124c825bca',
    type: 'TEXT',
    dataType: 'STRING',
    fieldName: 'firstName',
    fieldDisplayName: 'First Name',
    camera: false,
    editable: true,
    mandatory: true,
    displayOrder: 1,
    galleryEnabled: false,
    gpsenabled: false,
    description: 'aap ka pehla naam bhathaa',
    helpText: 'If your name is "John Doe" please enter "John"',
    fileTypes: [],
    multiQuestions: [],
    arrayType: false,
    children: [],
    value:''
  },
  {
    modelType: 'details',
    id: '622040bd83ee70124c825bca',
    type: 'TEXT',
    dataType: 'STRING',
    fieldName: 'lastName',
    fieldDisplayName: 'Last Name',
    camera: false,
    editable: true,
    mandatory: true,
    displayOrder: 1,
    galleryEnabled: false,
    gpsenabled: false,
    description: 'aap ka pehla naam bhathaa',
    helpText: 'If your name is "John Doe" please enter "John"',
    fileTypes: [],
    multiQuestions: [],
    arrayType: false,
    children: [],
    value:''
  },
  {
    modelType: 'details',
    id: '622040bd83ee70124c825bd8',
    type: 'NUMBER',
    dataType: 'DECIMAL',
    fieldName: 'phoneNumber',
    fieldDisplayName: 'Phone',
    camera: false,
    editable: true,
    mandatory: true,
    displayOrder: 1,
    galleryEnabled: false,
    gpsenabled: false,
    description: 'Calculate age of user in years',
    helpText: '',
    fileTypes: [],
    sampleImageURL: '',
    multiQuestions: [],
    arrayType: false,
    children: [],
    value:''
  },
  {
    modelType: 'details',
    id: '622040bd83ee70124c825bd8',
    type: 'email',
    dataType: 'email',
    fieldName: 'email',
    fieldDisplayName: 'Email',
    camera: false,
    editable: true,
    mandatory: true,
    displayOrder: 1,
    galleryEnabled: false,
    gpsenabled: false,
    description: 'Calculate age of user in years',
    helpText: '',
    fileTypes: [],
    sampleImageURL: '',
    multiQuestions: [],
    arrayType: false,
    children: [],
    value:''
  },
];
