export const experience = [
    {
        modelType: 'field',
        id: '622040bd83ee70124c825bd7',
        type: 'TEXT',
        dataType: 'STRING',
        fieldName: 'company_name',
        fieldDisplayName: 'Company Name',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: '',
        helpText: 'Enter any remarks while filling personal information page',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bd7',
        type: 'TEXT',
        dataType: 'STRING',
        fieldName: 'job_title',
        fieldDisplayName: 'Job Title',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: '',
        helpText: 'Enter any remarks while filling personal information page',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'date',
        fieldName: 'start_date',
        fieldDisplayName: 'Start Date',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'date',
        fieldName: 'end_date',
        fieldDisplayName: 'End Date',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      }
]