export const professionalDetails = [
    {
        modelType: 'exp',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'totalExperience',
        fieldDisplayName: 'Years',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: '1',
            value: '1',
          },
          {
            display: '2',
            value: '2',
          },
          {
            display: '3',
            value: '3',
          },
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'totalMonthOfExperience',
        fieldDisplayName: 'Months',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: '1',
            value: '1',
          },
          {
            display: '2',
            value: '2',
          },
          {
            display: '3',
            value: '3',
          },
          {
            display: '4',
            value: '4',
          },
          {
            display: '5',
            value: '5',
          },
          {
            display: '6',
            value: '6',
          },
          {
            display: '7',
            value: '7',
          },
          {
            display: '8',
            value: '8',
          },
          {
            display: '9',
            value: '9',
          },
          {
            display: '10',
            value: '10',
          },
          {
            display: '11',
            value: '11',
          },
          {
            display: '12',
            value: '12',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'relevantExperience',
        fieldDisplayName: 'Years',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: '1',
            value: '1',
          },
          {
            display: '2',
            value: '2',
          },
          {
            display: '3',
            value: '3',
          },
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'totalMonthOfRelevantExperience',
        fieldDisplayName: 'Months',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: '1',
            value: '1',
          },
          {
            display: '2',
            value: '2',
          },
          {
            display: '3',
            value: '3',
          },
          {
            display: '4',
            value: '4',
          },
          {
            display: '5',
            value: '5',
          },
          {
            display: '6',
            value: '6',
          },
          {
            display: '7',
            value: '7',
          },
          {
            display: '8',
            value: '8',
          },
          {
            display: '9',
            value: '9',
          },
          {
            display: '10',
            value: '10',
          },
          {
            display: '11',
            value: '11',
          },
          {
            display: '12',
            value: '12',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'DECIMAL',
        fieldName: 'currentSalaryPerYear',
        fieldDisplayName: 'Per Year',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'DECIMAL',
        fieldName: 'currentSalaryPerMonth',
        fieldDisplayName: 'Per Month',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'DECIMAL',
        fieldName: 'expectedSalaryPerYear',
        fieldDisplayName: 'Per Year',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'DECIMAL',
        fieldName: 'expectedSalaryPerMonth',
        fieldDisplayName: 'Per Month',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'exp',
        id: '622040bd83ee70124c825bd8',
        type: 'NUMBER',
        dataType: 'DECIMAL',
        fieldName: 'offeredValue',
        fieldDisplayName: 'Offered Value',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'Calculate age of user in years',
        helpText: '',
        fileTypes: [],
        sampleImageURL: '',
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'det',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'currentJobTitle',
        fieldDisplayName: 'Applied Role',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: 'React Developer',
            value: 'React Developer',
          },
          {
            display: 'Angular Developer',
            value: 'Angular Developer',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'det',
        id: '622040bd83ee70124c825bca',
        type: 'dropdown',
        dataType: 'STRING',
        fieldName: 'skillSet',
        fieldDisplayName: 'Skills',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        description: 'aap ka pehla naam bhathaa',
        helpText: 'If your name is "John Doe" please enter "John"',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        options: [
            {
              display: 'Angular',
              value: 'Angular',
            },
            {
              display: 'React',
              value: 'React',
            },
            {
              display: 'JS',
              value: 'JS',
            },
          ],
          value:''
      },
      // {
      //   modelType: 'det',
      //   id: '622040bd83ee70124c825bd8',
      //   type: 'NUMBER',
      //   dataType: 'DECIMAL',
      //   fieldName: 'exp_joining_date',
      //   fieldDisplayName: 'Expecting Join Date',
      //   camera: false,
      //   editable: true,
      //   mandatory: true,
      //   displayOrder: 1,
      //   galleryEnabled: false,
      //   gpsenabled: false,
      //   description: 'Calculate age of user in years',
      //   helpText: '',
      //   fileTypes: [],
      //   sampleImageURL: '',
      //   multiQuestions: [],
      //   arrayType: false,
      //   children: [],
      //   value:''
      // },
      {
        modelType: 'det',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'noticePeriod',
        fieldDisplayName: 'Notice Period',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: '15 Days',
            value: '15 Days',
          },
          {
            display: '30 Days',
            value: '30 Days',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      // {
      //   modelType: 'field',
      //   id: '622040bd83ee70124c825bcf',
      //   type: 'RADIO',
      //   dataType: 'STRING',
      //   fieldName: 'other_offers',
      //   fieldDisplayName: 'Other Offers',
      //   camera: false,
      //   editable: true,
      //   mandatory: true,
      //   displayOrder: 1,
      //   galleryEnabled: false,
      //   gpsenabled: false,
      //   options: [
      //     {
      //       display: 'Yes',
      //       value: 'Yes',
      //     },
      //     {
      //       display: 'No',
      //       value: 'No',
      //     }
      //   ],
      //   description: 'Marital status of individual',
      //   helpText: 'Marital status of individual',
      //   fileTypes: [],
      //   multiQuestions: [],
      //   arrayType: false,
      //   children: [],
      //   value:''
      // },
      // {
      //   modelType: 'field',
      //   id: '622040bd83ee70124c825bd8',
      //   type: 'NUMBER',
      //   dataType: 'DECIMAL',
      //   fieldName: 'offered_value',
      //   fieldDisplayName: 'Offered Value in LPA',
      //   camera: false,
      //   editable: true,
      //   mandatory: true,
      //   displayOrder: 1,
      //   galleryEnabled: false,
      //   gpsenabled: false,
      //   description: 'Calculate age of user in years',
      //   helpText: '',
      //   fileTypes: [],
      //   sampleImageURL: '',
      //   multiQuestions: [],
      //   arrayType: false,
      //   children: [],
      //   value:''
      // },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bcf',
        type: 'boolean',
        dataType: 'STRING',
        fieldName: 'servedNoticePeriod',
        fieldDisplayName: 'Serving Notice Period',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: 'Yes',
            value: 'Yes',
          },
          {
            display: 'No',
            value: 'No',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bcf',
        type: 'checkbox',
        dataType: 'boolean',
        fieldName: 'isNegotiable',
        fieldDisplayName: 'Is Negotiable',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'field',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'source',
        fieldDisplayName: 'Source',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: 'Yes',
            value: 'Yes',
          },
          {
            display: 'No',
            value: 'No',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      },
      {
        modelType: 'det',
        id: '622040bd83ee70124c825bcf',
        type: 'RADIO',
        dataType: 'STRING',
        fieldName: 'interviewBy',
        fieldDisplayName: 'Interview By',
        camera: false,
        editable: true,
        mandatory: true,
        displayOrder: 1,
        galleryEnabled: false,
        gpsenabled: false,
        options: [
          {
            display: 'Bharathi',
            value: 'Bharathi',
          },
          {
            display: 'Lakshmi Narasimha',
            value: 'Lakshmi Narasimha',
          }
        ],
        description: 'Marital status of individual',
        helpText: 'Marital status of individual',
        fileTypes: [],
        multiQuestions: [],
        arrayType: false,
        children: [],
        value:''
      }
]